#!/usr/bin/env python3
"""Generate the branded PDF showcase report for the homepage sample link.

Uses the same StudioPDF class and branding as /api/report/pdf but with
hardcoded case study data matching the homepage Trade-Off example.
"""
import os
import re
from fpdf import FPDF

OUTDIR = 'sample-reports'
os.makedirs(OUTDIR, exist_ok=True)

# ── Wade palette ──
NAVY = (30, 25, 79)
ORANGE = (241, 90, 34)
PINK = (237, 54, 148)
TEAL = (39, 189, 190)
YELLOW = (228, 229, 23)
DARK_GREY = (73, 71, 77)
MID_GREY = (168, 164, 165)
LIGHT_BG = (246, 245, 245)
WHITE = (255, 255, 255)

# ── Tier colours for value stack ──
TIER_COLOURS = {
    'must': TEAL,
    'strong': (255, 183, 77),   # amber
    'exp': PINK,
}


class StudioPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        font_dir = os.path.join(os.path.dirname(__file__), 'fonts')
        ttf_path = os.path.join(font_dir, 'GT-Walsheim-Regular.ttf')
        self._has_gt = os.path.exists(ttf_path)
        if self._has_gt:
            self.add_font('GTWalsheim', '', ttf_path)
            self._body = 'GTWalsheim'
        else:
            self._body = 'Helvetica'
        # Helvetica for B/I since GTWalsheim only has regular weight
        self._bold = 'Helvetica'

    @staticmethod
    def safe(text):
        """Replace Unicode chars that Helvetica can't render."""
        return text.replace('--', '--').replace('-', '-').replace('\u2019', "'").replace('\u201c', '"').replace('\u201d', '"')

    def footer(self):
        self.set_y(-15)
        self.set_font(self._body, '', 7)
        self.set_text_color(*MID_GREY)
        self.cell(0, 10, 'Generated by The Studio  |  Wade Institute of Entrepreneurship  |  wadeinstitute.org.au', align='C')


def build_showcase_pdf():
    pdf = StudioPDF()
    pw = pdf.w - pdf.l_margin - pdf.r_margin  # usable page width

    # ════════════════════════════════════════════
    # PAGE 1 — Cover
    # ════════════════════════════════════════════
    pdf.add_page()

    # Navy header bar
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, pdf.w, 22, 'F')

    logo = os.path.join(os.path.dirname(__file__), 'logo-orange.png')
    if os.path.exists(logo):
        pdf.image(logo, x=10, y=4, h=14)

    # Metadata
    pdf.set_font(pdf._body, '', 7)
    pdf.set_text_color(*MID_GREY)
    meta = 'THE TEST  |  THE TRADE-OFF  |  MARCH 2026'
    pdf.set_xy(pdf.w - 10 - pdf.get_string_width(meta), 8)
    pdf.cell(pdf.get_string_width(meta), 6, meta, align='R')

    pdf.set_y(34)

    # Title
    pdf.set_font(pdf._bold, 'B', 24)
    pdf.set_text_color(*NAVY)
    pdf.multi_cell(pw, 11, "Your Customers Don't Want\nEverything You're Building")
    pdf.ln(3)

    # Hook
    pdf.set_font(pdf._bold, 'I', 12)
    pdf.set_text_color(*DARK_GREY)
    pdf.multi_cell(pw, 7, 'You thought all seven features were essential. Six rounds of forced trade-offs revealed that only three survive contact with reality.')
    pdf.ln(6)

    # Orange rule
    pdf.set_draw_color(*ORANGE)
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + pw, pdf.get_y())
    pdf.ln(6)

    # Key numbers row
    numbers = [
        ('7', 'features tested'),
        ('6', 'rounds of trade-offs'),
        ('3', 'survivors'),
        ('$39/mo', 'minimum viable offer'),
    ]
    col_w = pw / len(numbers)
    y_num = pdf.get_y()
    for i, (num, label) in enumerate(numbers):
        x = pdf.l_margin + i * col_w
        pdf.set_font(pdf._bold, 'B', 22)
        pdf.set_text_color(*ORANGE)
        pdf.set_xy(x, y_num)
        pdf.cell(col_w, 10, num, align='C')
        pdf.set_font(pdf._body, '', 8)
        pdf.set_text_color(*MID_GREY)
        pdf.set_xy(x, y_num + 11)
        pdf.cell(col_w, 5, label, align='C')
    pdf.set_y(y_num + 22)
    pdf.ln(6)

    # Opening narrative
    pdf.set_font(pdf._body, '', 10)
    pdf.set_text_color(*DARK_GREY)
    pdf.multi_cell(pw, 6,
        'You came in with seven features planned for launch. A full-featured project management '
        'tool for mid-size creative agencies. "We need all of them," you said. Six rounds of forced '
        'trade-offs later, the picture looks very different.\n\n'
        'Three features dominate. Three are expendable. And the one you were most excited about '
        '-- real-time collaboration, the centrepiece of the pitch deck, the most technically '
        'complex thing you\'ve built -- lost five of six rounds.'
    )
    pdf.ln(4)

    # Challenge box
    pdf.set_fill_color(*LIGHT_BG)
    y_box = pdf.get_y()
    pdf.rect(pdf.l_margin, y_box, pw, 28, 'F')
    pdf.set_draw_color(*ORANGE)
    pdf.set_line_width(0.8)
    pdf.line(pdf.l_margin, y_box, pdf.l_margin, y_box + 28)
    pdf.set_font(pdf._bold, 'B', 10)
    pdf.set_text_color(*NAVY)
    pdf.set_xy(pdf.l_margin + 5, y_box + 3)
    pdf.cell(pw - 10, 5, 'The challenge')
    pdf.set_font(pdf._body, '', 9)
    pdf.set_text_color(*DARK_GREY)
    pdf.set_xy(pdf.l_margin + 5, y_box + 10)
    pdf.multi_cell(pw - 10, 5,
        'Building a project management SaaS for mid-size agencies (15-80 people). Seven features '
        'in the launch roadmap, limited runway, and a team convinced everything is equally important. '
        'The real question: if you can only ship three features at launch, which three?'
    )
    pdf.set_y(y_box + 32)

    # ════════════════════════════════════════════
    # PAGE 2 — The Setup & Rounds
    # ════════════════════════════════════════════
    pdf.add_page()

    # Section: The Setup
    _section_heading(pdf, pw, 'The Setup')

    # Features tested table
    features = [
        ('Automated weekly reporting', 'Client-facing status updates generated from task data'),
        ('One-click integrations', 'Slack, Google Drive, Xero without setup friction'),
        ('Time tracking', 'Built-in timer linked to tasks and invoicing'),
        ('White-label client portal', 'Branded view for external stakeholders'),
        ('Custom workflows', 'Drag-and-drop pipeline builder per client'),
        ('AI task suggestions', 'Auto-generates next steps based on project patterns'),
        ('Real-time collaboration', 'Live cursors, comments, co-editing inside the tool'),
    ]

    for name, desc in features:
        y = pdf.get_y()
        if y > pdf.h - 20:
            pdf.add_page()
        pdf.set_font(pdf._bold, 'B', 9)
        pdf.set_text_color(*NAVY)
        pdf.set_x(pdf.l_margin + 2)
        pdf.cell(60, 5, name)
        pdf.set_font(pdf._body, '', 9)
        pdf.set_text_color(*DARK_GREY)
        pdf.cell(pw - 62, 5, desc)
        pdf.ln(6)

    pdf.ln(4)

    # Section: The Six Rounds
    _section_heading(pdf, pw, 'The Six Rounds')
    pdf.set_font(pdf._body, '', 9)
    pdf.set_text_color(*DARK_GREY)
    pdf.multi_cell(pw, 5,
        'Each round forced a choice between competing feature bundles, stripping away comfort '
        'and forcing harder decisions. Here\'s what survived.'
    )
    pdf.ln(4)

    rounds_data = [
        ('Round 1', 'v The Agency Essential vs x The Bare Bones'),
        ('Round 2', 'v The Data Engine vs x The Network Play'),
        ('Round 3', 'v The Integration Hub vs x The Collab Suite'),
        ('Round 4', 'v The Lean Build vs x The Full Stack'),
        ('Round 5', 'v The Report Machine vs x The Innovation Kit'),
        ('Round 6', 'v The Core Three vs x The Feature Feast'),
    ]

    for tag, matchup in rounds_data:
        y = pdf.get_y()
        pdf.set_fill_color(*NAVY)
        pdf.rect(pdf.l_margin, y, pw, 8, 'F')
        pdf.set_font(pdf._bold, 'B', 8)
        pdf.set_text_color(*ORANGE)
        pdf.set_xy(pdf.l_margin + 3, y + 1.5)
        pdf.cell(25, 5, tag)
        pdf.set_font(pdf._body, '', 8)
        pdf.set_text_color(*WHITE)
        pdf.cell(pw - 28, 5, matchup)
        pdf.set_y(y + 9.5)

    pdf.ln(6)

    # ════════════════════════════════════════════
    # PAGE 3 — Value Stack & Analysis
    # ════════════════════════════════════════════
    pdf.add_page()

    _section_heading(pdf, pw, 'The Value Stack')

    tiers = [
        ('MUST-HAVE', 'must', 'Won 5-6 of 6', [
            ('Automated weekly reporting', '6/6 wins'),
            ('One-click integrations', '5/6 wins'),
        ]),
        ('NICE-TO-HAVE', 'strong', 'Won 3-4 of 6', [
            ('Time tracking', '4/6 wins'),
            ('White-label client portal', '3/6 wins'),
        ]),
        ('EXPENDABLE', 'exp', 'Won 0-2 of 6', [
            ('Custom workflows', '2/6 wins'),
            ('AI task suggestions', '1/6 wins'),
            ('Real-time collaboration', '1/6 wins'),
        ]),
    ]

    for tier_name, tier_class, tier_range, items in tiers:
        y = pdf.get_y()
        colour = TIER_COLOURS.get(tier_class, MID_GREY)

        # Tier header
        pdf.set_fill_color(*colour)
        pdf.rect(pdf.l_margin, y, pw, 8, 'F')
        pdf.set_font(pdf._bold, 'B', 9)
        pdf.set_text_color(*WHITE if tier_class != 'strong' else NAVY)
        pdf.set_xy(pdf.l_margin + 3, y + 1.5)
        pdf.cell(50, 5, tier_name)
        pdf.set_font(pdf._body, '', 8)
        pdf.cell(pw - 53, 5, tier_range, align='R')
        pdf.set_y(y + 9)

        # Tier items
        for name, wins in items:
            yi = pdf.get_y()
            pdf.set_fill_color(*LIGHT_BG)
            pdf.rect(pdf.l_margin, yi, pw, 7, 'F')
            # Thin left accent
            pdf.set_draw_color(*colour)
            pdf.set_line_width(0.6)
            pdf.line(pdf.l_margin, yi, pdf.l_margin, yi + 7)
            pdf.set_font(pdf._body, '', 9)
            pdf.set_text_color(*DARK_GREY)
            pdf.set_xy(pdf.l_margin + 4, yi + 1)
            pdf.cell(90, 5, name)
            pdf.set_font(pdf._bold, 'B', 9)
            pdf.set_text_color(*colour)
            pdf.cell(pw - 94, 5, wins, align='R')
            pdf.set_y(yi + 8)

        pdf.ln(2)

    pdf.ln(4)

    # The Surprise
    _section_heading(pdf, pw, 'The Surprise')
    pdf.set_fill_color(*LIGHT_BG)
    y_sur = pdf.get_y()
    pdf.rect(pdf.l_margin, y_sur, pw, 30, 'F')
    pdf.set_draw_color(*PINK)
    pdf.set_line_width(1.0)
    pdf.line(pdf.l_margin, y_sur, pdf.l_margin, y_sur + 30)
    pdf.set_font(pdf._body, '', 9)
    pdf.set_text_color(*DARK_GREY)
    pdf.set_xy(pdf.l_margin + 5, y_sur + 3)
    pdf.multi_cell(pw - 10, 5,
        'Real-time collaboration -- the feature you were most excited about, the centrepiece of your '
        'pitch deck, and the most technically complex thing you\'ve built -- lost five of six rounds. '
        'Meanwhile, automated reporting -- a feature you nearly cut for feeling "boring" -- won every '
        'single round. Your customers don\'t want what you love building. They want what saves them time.'
    )
    pdf.set_y(y_sur + 34)
    pdf.ln(4)

    # Minimum Viable Offer
    _section_heading(pdf, pw, 'Minimum Viable Offer')

    pdf.set_fill_color(*NAVY)
    y_mvo = pdf.get_y()
    pdf.rect(pdf.l_margin, y_mvo, pw, 36, 'F')

    pdf.set_font(pdf._bold, 'B', 11)
    pdf.set_text_color(*ORANGE)
    pdf.set_xy(pdf.l_margin + 6, y_mvo + 4)
    pdf.cell(pw - 12, 6, 'Reporting + Integrations + Time Tracking')

    pdf.set_font(pdf._bold, 'B', 18)
    pdf.set_text_color(*WHITE)
    pdf.set_xy(pdf.l_margin + 6, y_mvo + 13)
    pdf.cell(pw - 12, 8, '$39/month per seat')

    pdf.set_font(pdf._body, '', 8)
    pdf.set_text_color(*MID_GREY)
    pdf.set_xy(pdf.l_margin + 6, y_mvo + 24)
    pdf.multi_cell(pw - 12, 4,
        'The floor -- the cheapest version someone would still pay for. '
        'High level of every must-have, Low level of everything else.'
    )

    pdf.set_y(y_mvo + 40)

    # ════════════════════════════════════════════
    # PAGE 4 — Key Moments & Actions
    # ════════════════════════════════════════════
    pdf.add_page()

    _section_heading(pdf, pw, 'Key Moments')

    moments = [
        ('"I keep choosing reporting over collaboration -- I think our customers don\'t care about what we care about."',
         'The first sign that builder excitement and buyer need had diverged.'),
        ('"Automated reporting saves an agency owner 45 minutes every Monday. Collaboration saves us a cool demo."',
         'Reframed the entire value proposition from novelty to utility.'),
        ('"If I\'m honest, we built collaboration because it was fun to build. Not because anyone asked for it."',
         'The admission that changed the launch plan.'),
    ]

    for quote, why in moments:
        y = pdf.get_y()
        if y > pdf.h - 30:
            pdf.add_page()
        pdf.set_fill_color(*LIGHT_BG)
        pdf.rect(pdf.l_margin, y, pw, 18, 'F')
        pdf.set_draw_color(*ORANGE)
        pdf.set_line_width(0.7)
        pdf.line(pdf.l_margin, y, pdf.l_margin, y + 18)

        pdf.set_font(pdf._bold, 'I', 9)
        pdf.set_text_color(*NAVY)
        pdf.set_xy(pdf.l_margin + 5, y + 2)
        pdf.multi_cell(pw - 10, 5, quote)

        pdf.set_font(pdf._body, '', 8)
        pdf.set_text_color(*MID_GREY)
        pdf.set_xy(pdf.l_margin + 5, y + 11)
        pdf.cell(pw - 10, 5, why)
        pdf.set_y(y + 21)

    pdf.ln(4)

    # The Reframe
    _section_heading(pdf, pw, 'The Reframe')

    pdf.set_font(pdf._bold, 'B', 9)
    pdf.set_text_color(*MID_GREY)
    pdf.cell(pw, 5, 'BEFORE')
    pdf.ln(5)
    pdf.set_font(pdf._body, '', 9)
    pdf.set_text_color(*DARK_GREY)
    pdf.multi_cell(pw, 5, '"We need to ship all seven features to compete with Monday.com and Asana."')
    pdf.ln(3)

    pdf.set_font(pdf._bold, 'B', 9)
    pdf.set_text_color(*ORANGE)
    pdf.cell(pw, 5, 'AFTER')
    pdf.ln(5)
    pdf.set_font(pdf._body, '', 9)
    pdf.set_text_color(*DARK_GREY)
    pdf.multi_cell(pw, 5,
        '"We need to ship three features that save an agency owner 45 minutes every week -- '
        'and charge less than the tools that try to do everything."'
    )
    pdf.ln(6)

    # Actions
    _section_heading(pdf, pw, 'What to Do Next')

    actions = [
        ('This week', 'Founder + CTO', 'Rebuild launch scope around the three must-haves: reporting, integrations, time tracking. Cut everything else from v1.'),
        ('2 weeks', 'Founder', 'Run 5 customer interviews showing two pricing tiers -- core bundle at $39/mo vs full suite at $69/mo.'),
        ('2 weeks', 'Marketing', 'Rewrite positioning: lead with the boring feature. "Automated client reports in 30 seconds" is the headline.'),
        ('This week', 'CTO', 'Shelf the collaboration engine. Don\'t delete the code -- remove it from product and marketing until 50 paying customers ask for it.'),
    ]

    for timeframe, owner, action in actions:
        y = pdf.get_y()
        if y > pdf.h - 20:
            pdf.add_page()
        pdf.set_fill_color(*LIGHT_BG)
        pdf.rect(pdf.l_margin, y, pw, 14, 'F')

        # Orange timeline badge
        pdf.set_font(pdf._bold, 'B', 7)
        pdf.set_text_color(*ORANGE)
        pdf.set_xy(pdf.l_margin + 3, y + 1)
        pdf.cell(25, 4, timeframe.upper())

        # Owner
        pdf.set_font(pdf._body, '', 7)
        pdf.set_text_color(*MID_GREY)
        pdf.set_xy(pdf.l_margin + 30, y + 1)
        pdf.cell(30, 4, owner)

        # Action text
        pdf.set_font(pdf._body, '', 9)
        pdf.set_text_color(*DARK_GREY)
        pdf.set_xy(pdf.l_margin + 3, y + 6)
        pdf.multi_cell(pw - 6, 4, action)
        pdf.set_y(y + 16)

    pdf.ln(4)

    # Questions
    _section_heading(pdf, pw, 'Questions to Sit With')

    questions = [
        ('Product', 'Is the reporting engine genuinely best-in-class, or an afterthought that now needs real investment?'),
        ('Positioning', 'What does the pricing page look like leading with "Automated client reports in 30 seconds" instead of "All-in-one project management"?'),
        ('Honesty', 'Which expendable features are you still emotionally attached to -- and why?'),
        ('Competition', 'If a competitor launched with just reporting + integrations tomorrow, how would you respond?'),
    ]

    for tag, question in questions:
        y = pdf.get_y()
        if y > pdf.h - 15:
            pdf.add_page()
        pdf.set_font(pdf._bold, 'B', 7)
        pdf.set_text_color(*ORANGE)
        pdf.set_x(pdf.l_margin + 2)
        pdf.cell(5, 5, '-')
        pdf.set_font(pdf._bold, 'B', 8)
        pdf.set_text_color(*NAVY)
        pdf.cell(22, 5, tag.upper())
        pdf.set_font(pdf._body, '', 9)
        pdf.set_text_color(*DARK_GREY)
        pdf.multi_cell(pw - 29, 5, question)
        pdf.ln(2)

    # ════════════════════════════════════════════
    # PAGE 5 — Go Further (Wade CTA)
    # ════════════════════════════════════════════
    pdf.add_page()

    # Navy separator
    pdf.set_draw_color(*NAVY)
    pdf.set_line_width(0.5)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + pw, pdf.get_y())
    pdf.ln(8)

    pdf.set_font(pdf._bold, 'B', 18)
    pdf.set_text_color(*NAVY)
    pdf.cell(pw, 10, 'Go Further')
    pdf.ln(12)

    pdf.set_font(pdf._body, '', 10)
    pdf.set_text_color(*DARK_GREY)
    pdf.multi_cell(pw, 6,
        'This pattern -- building for the demo instead of the buyer -- is one of the most common '
        'reasons startups overbuild and underprice. The Trade-Off exercise surfaced it in 25 minutes. '
        'Imagine what a full program does.'
    )
    pdf.ln(6)

    cards = [
        ('Recommended reading', 'Explore more tools in The Studio to pressure-test your assumptions, validate demand, and build with confidence.'),
        ('Wade programs', 'Wade\'s flagship programs take you beyond the tools. Build your venture with a cohort of founders, expert mentors, and structured support.'),
        ('From the Wade community', '"I cut my roadmap in half after a single Trade-Off session. We launched three months earlier and doubled our conversion rate." -- James Nguyen, MoE \'24'),
    ]

    for heading, body in cards:
        y = pdf.get_y()
        pdf.set_fill_color(*LIGHT_BG)
        pdf.rect(pdf.l_margin, y, pw, 20, 'F')
        pdf.set_font(pdf._bold, 'B', 10)
        pdf.set_text_color(*NAVY)
        pdf.set_xy(pdf.l_margin + 4, y + 3)
        pdf.cell(pw - 8, 5, heading)
        pdf.set_font(pdf._body, '', 9)
        pdf.set_text_color(*DARK_GREY)
        pdf.set_xy(pdf.l_margin + 4, y + 10)
        pdf.multi_cell(pw - 8, 4, body)
        pdf.set_y(y + 24)

    # Save
    out_path = os.path.join(OUTDIR, 'showcase.pdf')
    pdf.output(out_path)
    size = os.path.getsize(out_path)
    print(f'  OK  {out_path} ({size:,} bytes)')
    return out_path


def _section_heading(pdf, pw, text):
    """Render an H2-style section heading with orange left accent."""
    y = pdf.get_y()
    pdf.set_draw_color(*ORANGE)
    pdf.set_line_width(1.2)
    pdf.line(pdf.l_margin, y, pdf.l_margin, y + 9)
    pdf.set_font(pdf._bold, 'B', 14)
    pdf.set_text_color(*NAVY)
    pdf.set_x(pdf.l_margin + 5)
    pdf.cell(pw - 5, 8, text)
    pdf.ln(11)


if __name__ == '__main__':
    build_showcase_pdf()
